spring:
  cloud:
    config:
     enabled: true
zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    simple:
      path: /simple/**
      serviceId: simple-service
ribbon: 
  eureka:
    enabled: true

eureka:
  client:
    enabled: true
  instance:
    hostname: ${vcap.application.uris[0]}