spring:
  application:
    name: simple-gateway
    
  cloud:
    config:
      enabled: false   #currently not working, there is an open bug - https://github.com/spring-cloud/spring-cloud-config/issues/829

server:
  port: 9090

zuul:
  ignoredServices: "*"
  prefix: /api
  routes:
    simple:
      path: /simple/**
#uncomment this line and comment the line below when running the application locally      
      url: http://localhost:8081 
#      serviceId: simple-service

ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 10000
  maxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  eureka:
    enabled: false
    
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
            
#disable basic authentication as spring cloud config enables it by default
security:
  basic:
    enabled: false

#disable registering with eureka when running locally    
eureka:
  client:
    enabled: false

endpoints:
  routes:
    sensitive: false
    
management:
  security:
    enabled: false    